# Generated by Django 4.2 on 2023-04-14 09:44

import app.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Место')),
                ('description_short', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('description_long', tinymce.models.HTMLField(blank=True, default='', verbose_name='Описание')),
                ('coordinates_lng', models.FloatField(max_length=25, verbose_name='Долгота')),
                ('coordinates_lat', models.FloatField(max_length=25, verbose_name='Широта')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.Images.choose_folder, verbose_name='Фото')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.places', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('position',),
            },
        ),
    ]
